### ISSUE TITLE
Fetch content from a single markdown file

### ISSUE THREAD

**Issue by thetronjohnson** [thetronjohnson/remotekochi#1]

**Comment by abrahamparayil** [comment]
Wouldn't it be great if each place had it's own markdown file? That way if the community wants to incorporate more information (review, star rating, accessibility, vegan food (?) etc.) you could do so easily. The added advantage being that you don't need to write `jsx` to add a new place.

**Comment by thetronjohnson** [comment]
Sounds like a better idea, I've been getting requests to expand the list to other locations so I think this approach would make better sense when organizing by locations

**Comment by abrahamparayil** [comment]
@thetronjohnson I've opened a PR for the same. :D
